"""Initial migration

Revision ID: 3c66fee58add
Revises: a689d8681ac4
Create Date: 2026-02-04 14:56:05.323948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c66fee58add'
down_revision = 'a689d8681ac4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
